service: retail-store-order-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  tracing:
    lambda: true
    apiGateway: true

functions:
  OrderServiceApi:
    handler: handler.handle
    events:
      - http:
          path: /{id}
          method: GET
      - http:
          path: /{id}
          method: POST
resources:
  Resources:
    ordersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ordersTable
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-esbuild
  - serverless-offline
