service: retail-store-product-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  environment:
    MONGODB_URI: ${ssm:/retailstore/productservice/database}

functions:
  ProductServiceApi:
    handler: handler.handle
    events:
      - http:
          path: /{sku}
          method: GET

plugins:
  - serverless-esbuild
  - serverless-offline
