service: retail-store-product-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1

functions:
  ProductServiceApi:
    handler: handler.handle
    events:
      - http:
          path: /
          method: GET

plugins:
  - serverless-esbuild

resources:
Resources:
  DBCluster:
    Type: "AWS::DocDB::DBCluster"
    Properties:
      DBClusterIdentifier: "RetailStoreCluster"

  DBInstance:
    Type: "AWS::DocDB::DBInstance"
    Properties:
      DBClusterIdentifier: "RetailStoreCluster"
      DBInstanceIdentifier: "ProductService"
      DBInstanceClass: "db.t3.medium"
    DependsOn: DBCluster
