name: Product Service

on:
  push:
    branches: [main]
    paths:
      - src/productService

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Build Service
        run: |
          cd src/productService            
          npm ci           
          npm run build --if-present
      - name: Deploy Service
        run: |
          cd src/productService/
          sudo npm install -g serverless
          sudo serverless config credentials --provider aws --key ${{ secrets.ACCESSKEY }} --secret ${{ secrets.SECRETKEY }}
          sudo serverless deploy --verbose
